#ifndef MODEL_MESH_H
#define MODEL_MESH_H

#include "Material.h"
#include "Shader.h"
#include <glm/glm.hpp>
#include <vector>

struct ModelVertex
{
    glm::vec3 position{0.0f};
    glm::vec3 normal{0.0f, 1.0f, 0.0f};
    glm::vec2 texCoords{0.0f};
    glm::vec3 tangent{1.0f, 0.0f, 0.0f};
    glm::vec3 bitangent{0.0f, 0.0f, 1.0f};
};

// GPU-owned mesh generated by the Assimp importer. It supports normal drawing
// and bounded instanced drawing. Material state remains outside gameplay
// ownership; ModelMesh never contains interaction or collision logic.
class ModelMesh
{
public:
    ModelMesh(std::vector<ModelVertex> vertices,
              std::vector<unsigned int> indices,
              const Material& material);
    ~ModelMesh();

    ModelMesh(const ModelMesh&) = delete;
    ModelMesh& operator=(const ModelMesh&) = delete;
    ModelMesh(ModelMesh&& other) noexcept;
    ModelMesh& operator=(ModelMesh&& other) noexcept;

    void Draw(const Shader& shader) const;
    void DrawInstanced(const Shader& shader, const std::vector<glm::mat4>& modelMatrices) const;

    const Material& GetMaterial() const { return m_material; }

private:
    void SetupMesh();
    void Release();
    void EnsureInstanceBuffer(size_t matrixCount) const;

    std::vector<ModelVertex> m_vertices;
    std::vector<unsigned int> m_indices;
    Material m_material;

    unsigned int m_vao = 0;
    unsigned int m_vbo = 0;
    unsigned int m_ebo = 0;
    mutable unsigned int m_instanceVBO = 0;
    mutable size_t m_instanceCapacity = 0;
};

#endif // MODEL_MESH_H
